steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/mokeefe-sandbox/moonphases:latest', '.']
  timeout: 500s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/mokeefe-sandbox/moonphases:latest']
  timeout: 500s
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['delete', 'pod', '--selector=app=moonphases']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'
- name: 'gcr.io/cloud-builders/kubectl'
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'kubernetes/moonphases.yml']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'kubernetes/istio-egress-usno.yml']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'
