// Code generated by protoc-gen-go. DO NOT EDIT.
// source: phases.proto

package phases

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PhaseInfo struct {
	City                 string   `protobuf:"bytes,1,opt,name=City,proto3" json:"City,omitempty"`
	Lat                  string   `protobuf:"bytes,2,opt,name=Lat,proto3" json:"Lat,omitempty"`
	Lon                  string   `protobuf:"bytes,3,opt,name=Lon,proto3" json:"Lon,omitempty"`
	ClosestPhase         string   `protobuf:"bytes,4,opt,name=ClosestPhase,proto3" json:"ClosestPhase,omitempty"`
	Rise                 string   `protobuf:"bytes,5,opt,name=Rise,proto3" json:"Rise,omitempty"`
	UpperTransit         string   `protobuf:"bytes,6,opt,name=UpperTransit,proto3" json:"UpperTransit,omitempty"`
	Set                  string   `protobuf:"bytes,7,opt,name=Set,proto3" json:"Set,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhaseInfo) Reset()         { *m = PhaseInfo{} }
func (m *PhaseInfo) String() string { return proto.CompactTextString(m) }
func (*PhaseInfo) ProtoMessage()    {}
func (*PhaseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f10dcc001258d8cb, []int{0}
}

func (m *PhaseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhaseInfo.Unmarshal(m, b)
}
func (m *PhaseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhaseInfo.Marshal(b, m, deterministic)
}
func (m *PhaseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhaseInfo.Merge(m, src)
}
func (m *PhaseInfo) XXX_Size() int {
	return xxx_messageInfo_PhaseInfo.Size(m)
}
func (m *PhaseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PhaseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PhaseInfo proto.InternalMessageInfo

func (m *PhaseInfo) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *PhaseInfo) GetLat() string {
	if m != nil {
		return m.Lat
	}
	return ""
}

func (m *PhaseInfo) GetLon() string {
	if m != nil {
		return m.Lon
	}
	return ""
}

func (m *PhaseInfo) GetClosestPhase() string {
	if m != nil {
		return m.ClosestPhase
	}
	return ""
}

func (m *PhaseInfo) GetRise() string {
	if m != nil {
		return m.Rise
	}
	return ""
}

func (m *PhaseInfo) GetUpperTransit() string {
	if m != nil {
		return m.UpperTransit
	}
	return ""
}

func (m *PhaseInfo) GetSet() string {
	if m != nil {
		return m.Set
	}
	return ""
}

type GetPhasesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPhasesRequest) Reset()         { *m = GetPhasesRequest{} }
func (m *GetPhasesRequest) String() string { return proto.CompactTextString(m) }
func (*GetPhasesRequest) ProtoMessage()    {}
func (*GetPhasesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f10dcc001258d8cb, []int{1}
}

func (m *GetPhasesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPhasesRequest.Unmarshal(m, b)
}
func (m *GetPhasesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPhasesRequest.Marshal(b, m, deterministic)
}
func (m *GetPhasesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPhasesRequest.Merge(m, src)
}
func (m *GetPhasesRequest) XXX_Size() int {
	return xxx_messageInfo_GetPhasesRequest.Size(m)
}
func (m *GetPhasesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPhasesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPhasesRequest proto.InternalMessageInfo

type GetPhasesResponse struct {
	PhaseInfo            *PhaseInfo `protobuf:"bytes,1,opt,name=PhaseInfo,proto3" json:"PhaseInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetPhasesResponse) Reset()         { *m = GetPhasesResponse{} }
func (m *GetPhasesResponse) String() string { return proto.CompactTextString(m) }
func (*GetPhasesResponse) ProtoMessage()    {}
func (*GetPhasesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f10dcc001258d8cb, []int{2}
}

func (m *GetPhasesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPhasesResponse.Unmarshal(m, b)
}
func (m *GetPhasesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPhasesResponse.Marshal(b, m, deterministic)
}
func (m *GetPhasesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPhasesResponse.Merge(m, src)
}
func (m *GetPhasesResponse) XXX_Size() int {
	return xxx_messageInfo_GetPhasesResponse.Size(m)
}
func (m *GetPhasesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPhasesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPhasesResponse proto.InternalMessageInfo

func (m *GetPhasesResponse) GetPhaseInfo() *PhaseInfo {
	if m != nil {
		return m.PhaseInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*PhaseInfo)(nil), "phases.PhaseInfo")
	proto.RegisterType((*GetPhasesRequest)(nil), "phases.GetPhasesRequest")
	proto.RegisterType((*GetPhasesResponse)(nil), "phases.GetPhasesResponse")
}

func init() { proto.RegisterFile("phases.proto", fileDescriptor_f10dcc001258d8cb) }

var fileDescriptor_f10dcc001258d8cb = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0x03, 0x41,
	0x0c, 0x86, 0x5d, 0x5b, 0x57, 0x36, 0xf6, 0xd0, 0xe6, 0x14, 0x3d, 0xc9, 0x9c, 0x3c, 0x55, 0xa8,
	0x6f, 0x60, 0x05, 0x11, 0x14, 0xca, 0x54, 0x1f, 0x60, 0x85, 0x88, 0x0b, 0x32, 0x19, 0x37, 0xf1,
	0xe0, 0x63, 0xf9, 0x86, 0x32, 0x33, 0x75, 0x5d, 0xa5, 0xb7, 0x7f, 0xbf, 0x6c, 0xbe, 0x4c, 0x02,
	0xb3, 0xf8, 0xda, 0x2a, 0xeb, 0x32, 0xf6, 0x62, 0x82, 0x75, 0xf9, 0x72, 0x5f, 0x15, 0x34, 0x9b,
	0x14, 0xef, 0xc2, 0x8b, 0x20, 0xc2, 0x74, 0xdd, 0xd9, 0x27, 0x55, 0xe7, 0xd5, 0x45, 0xe3, 0x73,
	0xc6, 0x39, 0x4c, 0xee, 0x5b, 0xa3, 0xc3, 0x8c, 0x52, 0xcc, 0x44, 0x02, 0x4d, 0x76, 0x44, 0x02,
	0x3a, 0x98, 0xad, 0xdf, 0x44, 0x59, 0x2d, 0xbb, 0x68, 0x9a, 0x4b, 0x7f, 0x58, 0x72, 0xfb, 0x4e,
	0x99, 0x8e, 0x8a, 0x3b, 0xe5, 0xd4, 0xf7, 0x14, 0x23, 0xf7, 0x8f, 0x7d, 0x1b, 0xb4, 0x33, 0xaa,
	0x4b, 0xdf, 0x98, 0xa5, 0x69, 0x5b, 0x36, 0x3a, 0x2e, 0xd3, 0xb6, 0x6c, 0x0e, 0x61, 0x7e, 0xcb,
	0xc5, 0xaa, 0x9e, 0xdf, 0x3f, 0x58, 0xcd, 0xdd, 0xc0, 0x62, 0xc4, 0x34, 0x4a, 0x50, 0xc6, 0xcb,
	0xd1, 0x6e, 0x79, 0xa7, 0x93, 0xd5, 0x62, 0xb9, 0x3b, 0xc3, 0x50, 0xf0, 0xbf, 0xff, 0xac, 0x36,
	0x00, 0x0f, 0x22, 0xa1, 0x68, 0xf0, 0x1a, 0x9a, 0xc1, 0x89, 0xf4, 0xd3, 0xf8, 0x7f, 0xf4, 0xd9,
	0xe9, 0x9e, 0x4a, 0x79, 0x80, 0x3b, 0x78, 0xae, 0xf3, 0xb9, 0xaf, 0xbe, 0x03, 0x00, 0x00, 0xff,
	0xff, 0xa1, 0x87, 0x0d, 0x18, 0x7e, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MoonPhasesClient is the client API for MoonPhases service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MoonPhasesClient interface {
	GetPhases(ctx context.Context, in *GetPhasesRequest, opts ...grpc.CallOption) (*GetPhasesResponse, error)
}

type moonPhasesClient struct {
	cc *grpc.ClientConn
}

func NewMoonPhasesClient(cc *grpc.ClientConn) MoonPhasesClient {
	return &moonPhasesClient{cc}
}

func (c *moonPhasesClient) GetPhases(ctx context.Context, in *GetPhasesRequest, opts ...grpc.CallOption) (*GetPhasesResponse, error) {
	out := new(GetPhasesResponse)
	err := c.cc.Invoke(ctx, "/phases.MoonPhases/GetPhases", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MoonPhasesServer is the server API for MoonPhases service.
type MoonPhasesServer interface {
	GetPhases(context.Context, *GetPhasesRequest) (*GetPhasesResponse, error)
}

func RegisterMoonPhasesServer(s *grpc.Server, srv MoonPhasesServer) {
	s.RegisterService(&_MoonPhases_serviceDesc, srv)
}

func _MoonPhases_GetPhases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPhasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoonPhasesServer).GetPhases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phases.MoonPhases/GetPhases",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoonPhasesServer).GetPhases(ctx, req.(*GetPhasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MoonPhases_serviceDesc = grpc.ServiceDesc{
	ServiceName: "phases.MoonPhases",
	HandlerType: (*MoonPhasesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPhases",
			Handler:    _MoonPhases_GetPhases_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "phases.proto",
}
